services:
  mongodb:
    image: mongo
    restart: unless-stopped
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ""
      MONGO_INITDB_ROOT_PASSWORD: ""
  fodinha_rs:
    build: https://github.com/Lothyriel/oh_hell_rs.git
    environment:
      JWT_KEY: "JWT_KEY-oh_hell_rs"
    ports:
      - 3000:3000
